### PR TITLE
Add new CESM2 History File Example

### PR DESCRIPTION
**Pull request by mgrover1**
Went through and added additional instructions, markdown, etc. Only issue right now is reading back in the catalog using intake-esm (see #28 )

### CODE REVIEW

**Comment by andersy005** [comment]
@mgrover1, in #31 I moved this notebook in the `notebooks` directory (just wanted to give you a heads up in case you do a `git pull` and run into some conflicts). 

Let me know if #31 fully addresses #28


Also, do you have the pre-commit hooks activated on your local clone? (I am noticing that the linting CI is complaining)...

**Comment by mgrover1** [comment]
@andersy005 I keep running into this issue when running the pre-commit hooks
```
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    error: RPC failed; result=22, HTTP code = 422
    fatal: The remote end hung up unexpectedly
    
Check the log at /glade/u/home/mgrover/.cache/pre-commit/pre-commit.log
```

**Comment by andersy005** [comment]
What's the output of 

```bash 
git --version
``` 

and 

```bash 
which git
```

**Comment by mgrover1** [comment]
> ```shell
> git --version
> ```
git version 1.8.3.1

> ```shell
> which git
> ```
/usr/bin/git

**Comment by andersy005** [comment]
I'm going to speculate that the git you are using is the culprit here... That version is very old (~9 years old)... On cheyenne and casper, I usually avoid using the system libraries and use ones that are made available via `lmod` modules...

Try the following 
- Uninstall the pre-commit  hooks: `pre-commit uninstall` 
- Load a newer version of git and save your profile:  `module load git && module save` 
- Install pre-commit hooks again: `pre-commit install`

**Pull request closed without merging**
